# Data Processing

In [221]:
import numpy as np
import pandas as pd
import ast
import re

from nltk.app.chartparser_app import app

In [222]:
movies_df = pd.read_csv('Dataset/tmdb_5000_movies.csv')
credits_df = pd.read_csv('Dataset/tmdb_5000_credits.csv')

In [223]:
movies_df = movies_df.merge(credits_df, on="title")

In [224]:
movies_df.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

### We are going to keep:
1. Genre
2. Keywords
3. Id (For fetching posters)
4. Title
5. Overview (For making Tags)
6. Cast
7. Crew

In [225]:
movies_df = movies_df[['id', 'title', 'overview', 'genres', 'keywords', 'cast', 'crew']]

In [226]:
movies_df.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

### Missing/Duplicate Data

In [227]:
movies_df.dropna(inplace= True)

In [228]:
movies_df.isnull().sum()

id          0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [229]:
movies_df.duplicated().sum()

np.int64(0)

### Processing Genres, Keywords, Cast, Crews Columns

In [230]:
movies_df.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [231]:
def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i["name"])
    return L

In [232]:
movies_df["genres"] = movies_df["genres"].apply(convert)
movies_df["keywords"] = movies_df["keywords"].apply(convert)

In [233]:
movies_df.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [234]:
def convert_targeted(obj):
    L = []
    counter = 0
    for i in ast.literal_eval(obj):
        if counter != 5:
            L.append(i["name"])
            counter += 1
        else:
            break
    return L

In [235]:
movies_df['cast'] = movies_df['cast'].apply(convert_targeted)

In [236]:
movies_df.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [237]:
movies_df.iloc[0]['crew']

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [238]:
def fetchDirector(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L

In [239]:
movies_df['crew'] = movies_df['crew'].apply(fetchDirector)

In [240]:
movies_df.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

In [241]:
movies_df['overview'] = movies_df['overview'].apply(lambda x:x.split())

In [242]:
movies_df.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

### Removing Space from Tag materials

In [243]:
movies_df['genres'] = movies_df['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies_df['keywords'] = movies_df['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies_df['cast'] = movies_df['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies_df['crew'] = movies_df['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [244]:
movies_df.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton]

### Creating a Tag column

In [245]:
movies_df['tags'] = movies_df['genres'] + movies_df['keywords'] + movies_df['cast'] + movies_df['crew'] + movies_df['overview']

In [246]:
movies_df_formatted = movies_df[['id', 'title', 'tags']]

In [247]:
movies_df_formatted

,id,title,tags
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction, c..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action, ocean, drugabuse,..."
2,206647,Spectre,"[Action, Adventure, Crime, spy, basedonnovel, ..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller, dccomics, cri..."
4,49529,John Carter,"[Action, Adventure, ScienceFiction, basedonnov..."
...,...,...,...
4804,9367,El Mariachi,"[Action, Crime, Thriller, unitedstates–mexicob..."
4805,72766,Newlyweds,"[Comedy, Romance, EdwardBurns, KerryBishé, Mar..."
4806,231617,"Signed, Sealed, Delivered","[Comedy, Drama, Romance, TVMovie, date, loveat..."
4807,126186,Shanghai Calling,"[DanielHenney, ElizaCoupe, BillPaxton, AlanRuc..."
4808,25975,My Date with Drew,"[Documentary, obsession, camcorder, crush, dre..."

In [248]:
movies_df_formatted['tags'] = movies_df_formatted['tags'].apply(lambda x: " ".join(x))

In [249]:
movies_df_formatted

,id,title,tags
0,19995,Avatar,Action Adventure Fantasy ScienceFiction cultur...
1,285,Pirates of the Caribbean: At World's End,Adventure Fantasy Action ocean drugabuse exoti...
2,206647,Spectre,Action Adventure Crime spy basedonnovel secret...
3,49026,The Dark Knight Rises,Action Crime Drama Thriller dccomics crimefigh...
4,49529,John Carter,Action Adventure ScienceFiction basedonnovel m...
...,...,...,...
4804,9367,El Mariachi,Action Crime Thriller unitedstates–mexicobarri...
4805,72766,Newlyweds,Comedy Romance EdwardBurns KerryBishé MarshaDi...
4806,231617,"Signed, Sealed, Delivered",Comedy Drama Romance TVMovie date loveatfirsts...
4807,126186,Shanghai Calling,DanielHenney ElizaCoupe BillPaxton AlanRuck Zh...
4808,25975,My Date with Drew,Documentary obsession camcorder crush dreamgir...

In [250]:
movies_df_formatted['tags'] = movies_df_formatted['tags'].apply(lambda x: x.lower())
movies_df_formatted['tags'] = movies_df_formatted['tags'].apply(lambda x: re.sub(r'[^\w\s]', '', x))

In [251]:
movies_df_formatted

,id,title,tags
0,19995,Avatar,action adventure fantasy sciencefiction cultur...
1,285,Pirates of the Caribbean: At World's End,adventure fantasy action ocean drugabuse exoti...
2,206647,Spectre,action adventure crime spy basedonnovel secret...
3,49026,The Dark Knight Rises,action crime drama thriller dccomics crimefigh...
4,49529,John Carter,action adventure sciencefiction basedonnovel m...
...,...,...,...
4804,9367,El Mariachi,action crime thriller unitedstatesmexicobarrie...
4805,72766,Newlyweds,comedy romance edwardburns kerrybishé marshadi...
4806,231617,"Signed, Sealed, Delivered",comedy drama romance tvmovie date loveatfirsts...
4807,126186,Shanghai Calling,danielhenney elizacoupe billpaxton alanruck zh...
4808,25975,My Date with Drew,documentary obsession camcorder crush dreamgir...

# Vectorization

In [257]:
import nltk
from nltk.stem import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer

In [258]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Arpo\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.

True

In [259]:
ps = PorterStemmer()

def stemText(text):
    out = []
    for i in text.split():
        out.append(ps.stem(i))
    return " ".join(out)

In [260]:
movies_df_formatted['tags'] = movies_df_formatted['tags'].apply(stemText)

In [261]:
vectorizer = TfidfVectorizer(
    max_features= 5000,
    stop_words= 'english'
)
X = vectorizer.fit_transform(movies_df_formatted['tags'])
vectors = X.toarray()

In [262]:
vectors[0]

array([0., 0., 0., ..., 0., 0., 0.], shape=(5000,))

In [266]:
np.set_printoptions(threshold=np.inf)
print(vectorizer.get_feature_names_out())

['007' '10' '100' '10yearold' '11' '12' '12yearold' '13' '15' '16'
 '16yearold' '17' '17yearold' '18' '18th' '18thcenturi' '1910' '1920'
 '1930' '1940' '1950' '1960' '1970' '1974' '1976' '1980' '1985' '1990'
 '19th' '19thcenturi' '20' '2009' '20th' '24' '25' '30' '3d' '40' '50'
 '60' '70' 'aaron' 'aaroneckhart' 'aarontaylorjohnson' 'abandon' 'abbi'
 'abduct' 'abigailbreslin' 'abil' 'abl' 'aboard' 'aborigin' 'abov'
 'absenc' 'abus' 'academ' 'academi' 'accept' 'access' 'accid' 'accident'
 'acclaim' 'accompani' 'accomplish' 'account' 'accus' 'ace' 'achiev'
 'acquaint' 'act' 'action' 'actionhero' 'actionpack' 'activ' 'activist'
 'actor' 'actress' 'actual' 'ad' 'adam' 'adambrodi' 'adamsandl'
 'adamscott' 'adamshankman' 'adapt' 'add' 'addict' 'addit' 'adjust'
 'admir' 'admit' 'adolesc' 'adopt' 'ador' 'adrienbrodi' 'adult'
 'adultanim' 'adulteri' 'adulthood' 'advanc' 'advantag' 'adventur'
 'advertis' 'advic' 'advis' 'affair' 'affect' 'afghanistan' 'africa'
 'african' 'africanamerican' 'aftercreditssting' 'afterlif' 'aftermath'
 'age' 'agediffer' 'agenc' 'agenda' 'agent' 'aggress' 'ago' 'agre' 'ahead'
 'aid' 'aidanquinn' 'ail' 'aim' 'air' 'airplan' 'airplanecrash' 'airport'
 'aka' 'al' 'alabama' 'alan' 'alanalda' 'alanarkin' 'alanrickman' 'alaska'
 'albert' 'albertbrook' 'alcatraz' 'alcohol' 'alecbaldwin' 'alecguin'
 'alex' 'alexapenavega' 'alexisbledel' 'alexkendrick' 'alfredhitchcock'
 'alfredmolina' 'alfrewoodard' 'ali' 'alic' 'alicebraga' 'alien'
 'alieninvas' 'alienlifeform' 'alienplanet' 'alik' 'alilart' 'aliv'
 'alleg' 'allen' 'alli' 'allianc' 'allisonjanney' 'allow' 'alon'
 'alongsid' 'alpacino' 'alpha' 'alreadi' 'alter' 'altern' 'alway' 'alyssa'
 'alzheim' 'amanda' 'amandapeet' 'amandaseyfri' 'amateur' 'amaz' 'amazon'
 'ambassador' 'amberheard' 'ambit' 'ambiti' 'ambul' 'ambush' 'america'
 'american' 'americanabroad' 'americancivilwar' 'americanfootbal'
 'americanfootballplay' 'ami' 'amid' 'amidst' 'amnesia' 'amp' 'amsterdam'
 'amus' 'amusementpark' 'amyadam' 'amysmart' 'analyst' 'anarchiccomedi'
 'ancient' 'ancientrom' 'ancientworld' 'anderson' 'andi' 'andiemacdowel'
 'andrew' 'android' 'andygarcía' 'andysamberg' 'andyserki' 'angel'
 'angelabassett' 'angelinajoli' 'anger' 'angle' 'angri' 'ani' 'anim'
 'animalattack' 'animalhorror' 'anjelicahuston' 'ann' 'anna' 'annafari'
 'annakendrick' 'annapaquin' 'annasophiarobb' 'annehathaway' 'annehech'
 'annetteben' 'anni' 'anniversari' 'announc' 'annual' 'anonym' 'anoth'
 'answer' 'ant' 'antholog' 'anthoni' 'anthonyanderson' 'anthonyhopkin'
 'anthonymacki' 'anthropomorph' 'antic' 'antihero' 'antiqu' 'antisemit'
 'antoinefuqua' 'antoniobandera' 'antonyelchin' 'anyon' 'anyth' 'apart'
 'apartheid' 'ape' 'apocalyps' 'appar' 'appear' 'appl' 'appoint' 'appreci'
 'apprentic' 'approach' 'april' 'aquarium' 'arab' 'archaeologist'
 'archeolog' 'archer' 'architect' 'arctic' 'area' 'arena' 'arent'
 'argument' 'aris' 'aristocrat' 'arm' 'armi' 'armiehamm' 'armor'
 'armsdeal' 'arnold' 'arnoldschwarzenegg' 'arrang' 'arrangedmarriag'
 'arrest' 'arriv' 'arrog' 'art' 'arthur' 'articl' 'artifact' 'artifici'
 'artificialintellig' 'artist' 'ash' 'ashley' 'ashleyjudd' 'ashtonkutch'
 'asia' 'asid' 'ask' 'aspect' 'aspir' 'assassin' 'assault' 'assembl'
 'assign' 'assist' 'associ' 'assum' 'asteroid' 'astronaut' 'asylum'
 'atheist' 'athlet' 'atlant' 'atom' 'atomicbomb' 'attach' 'attack'
 'attempt' 'attempttoescap' 'attend' 'attent' 'attic' 'attitud' 'attorney'
 'attract' 'auction' 'audienc' 'audit' 'august' 'aunt' 'austin'
 'australia' 'australian' 'author' 'autism' 'auto' 'automobilerac' 'aveng'
 'averag' 'avoid' 'await' 'awak' 'awaken' 'awar' 'award' 'away' 'awesom'
 'awkward' 'awri' 'ax' 'babe' 'babi' 'bachelor' 'backdrop' 'background'
 'backpack' 'bad' 'badli' 'bag' 'bahama' 'bail' 'balanc' 'ball' 'ballet'
 'balloon' 'baltimor' 'ban' 'band' 'bandit' 'bangkok' 'banish' 'bank'
 'banker' 'bankrobb' 'bankrobberi' 'bar' 'barbarahershey' 'barbarian'
 'barbrastreisand' 'bare' 'bargain' 'barn' 'barney' 'baron' 'barri'
 'barrier' 'barrylevinson' 'barrypepp' 'barrysonnenfeld' 'base' 'basebal'
 'basedoncomicbook' 'basedongraphicnovel' 'basedonnovel' 'basedonplay'
 'basedonstagemus' 'basedontrueev' 'basedontruestori' 'basedontvseri'
 'basedonvideogam' 'basedonyoungadultnovel' 'basement' 'basketbal' 'bat'
 'batman' 'battl' 'battlefield' 'bay' 'beach' 'beam' 'bear' 'beard'
 'beast' 'beat' 'beauti' 'beautifulwoman' 'becam' 'becaus' 'becki' 'becom'
 'becominganadult' 'bed' 'bedroom' 'bee' 'beer' 'befor' 'befriend' 'began'
 'begin' 'behavior' 'belief' 'believ' 'bell' 'bella' 'belong' 'belov'
 'ben' 'benaffleck' 'beneath' 'benefit' 'benfost' 'beniciodeltoro'
 'benjamin' 'benjaminbratt' 'benkingsley' 'bennett' 'benstil' 'bent'
 'berlin' 'berniemac' 'best' 'bestfriend' 'bestfriendsinlov' 'bestsel'
 'bet' 'beth' 'betray' 'bettemidl' 'better' 'betti' 'beverli' 'bibl' 'bid'
 'big' 'bigciti' 'bigger' 'biggest' 'biker' 'bikini' 'billhad' 'billi'
 'billionair' 'billmurray' 'billnighi' 'billpaxton' 'billpullman'
 'billybobthornton' 'billyconnolli' 'billycrudup' 'billycryst' 'biographi'
 'biolog' 'bird' 'birth' 'birthday' 'bisexu' 'bishop' 'bit' 'bite'
 'bitter' 'bizarr' 'black' 'blackandwhit' 'blackmag' 'blackmail'
 'blackpeopl' 'blade' 'blame' 'blend' 'blind' 'bliss' 'block' 'blond'
 'blood' 'bloodi' 'bloodsplatt' 'bloodthirsti' 'blossom' 'blow' 'blue'
 'board' 'boat' 'bob' 'bobbi' 'bobbyfarrelli' 'bobhoskin' 'bodi'
 'bodyguard' 'bold' 'bollywood' 'bomb' 'bond' 'bone' 'bonniehunt' 'book'
 'boot' 'border' 'bore' 'boredom' 'born' 'borrow' 'boss' 'boston' 'botch'
 'bounc' 'bound' 'boundari' 'bounti' 'bountyhunt' 'bourn' 'bout' 'box'
 'boxer' 'boy' 'boyfriend' 'brad' 'braddourif' 'bradleycoop' 'bradpitt'
 'brain' 'brainwash' 'brand' 'brandon' 'brave' 'braveri' 'brazil'
 'brazilian' 'break' 'breakdown' 'breakup' 'breckinmey' 'breed'
 'brendanfras' 'brendangleeson' 'brent' 'brettratn' 'brian' 'briancox'
 'briandepalma' 'bride' 'bridesmaid' 'bridg' 'brief' 'brielarson' 'bright'
 'brilliant' 'bring' 'brink' 'britain' 'british' 'britishsecretservic'
 'brittanymurphi' 'broadcast' 'broadway' 'broke' 'broken' 'broker' 'bronx'
 'brook' 'brooklyn' 'broom' 'brothel' 'brother'
 'brotherbrotherrelationship' 'brotherinlaw' 'brothersisterrelationship'
 'brought' 'brown' 'bruce' 'brucecampbel' 'brucedern' 'brucegreenwood'
 'brucemcgil' 'brucewilli' 'brutal' 'bryansing' 'brycedallashoward' 'bu'
 'buck' 'bud' 'buddi' 'buddycomedi' 'buddycop' 'budget' 'bug' 'build'
 'built' 'bullet' 'bulli' 'bumbl' 'bunch' 'bunker' 'bunni' 'burglar'
 'buri' 'burn' 'burtreynold' 'busi' 'businessman' 'bust' 'butcher'
 'butler' 'button' 'buy' 'buzz' 'cabin' 'caesar' 'cage' 'cain' 'cairo'
 'cal' 'california' 'calvin' 'camcord' 'came' 'camera' 'cameraman'
 'camerondiaz' 'camgigandet' 'camp' 'campaign' 'campbel' 'campbellscott'
 'campu' 'canada' 'canadian' 'cancer' 'candi' 'candid' 'canin' 'cannib'
 'canuxploit' 'capabl' 'caper' 'capit' 'capt' 'captain' 'captiv' 'captur'
 'car' 'caraccid' 'carchas' 'carcrash' 'card' 'care' 'career' 'carefre'
 'caretak' 'careymulligan' 'caribbean' 'carjourney' 'carl' 'carlagugino'
 'carmen' 'carniv' 'carol' 'carolina' 'carrac' 'carri' 'carrieannemoss'
 'cartel' 'carter' 'cartoon' 'caryelw' 'case' 'caseyaffleck' 'cash'
 'casino' 'cast' 'castl' 'cat' 'cataclysm' 'catandmous' 'catastroph'
 'catch' 'cateblanchett' 'catherinekeen' 'catherineohara'
 'catherinezetajon' 'cathol' 'catholic' 'cattl' 'caught' 'caus' 'cavalri'
 'cave' 'cavemen' 'cedrictheentertain' 'celebr' 'cell' 'cellphon'
 'cemeteri' 'center' 'central' 'centuri' 'ceremoni' 'certain' 'chain'
 'chainsaw' 'challeng' 'chamber' 'champion' 'championship' 'chanc' 'chang'
 'channingtatum' 'chao' 'chaotic' 'chapter' 'charact' 'charg' 'charismat'
 'charl' 'charlessdutton' 'charli' 'charliesheen' 'charlizetheron'
 'charlott' 'charlotterampl' 'charm' 'chase' 'chazzpalminteri' 'cheat'
 'check' 'cheerlead' 'chef' 'chemic' 'cher' 'chevychas' 'chicago'
 'chicken' 'chief' 'child' 'childabus' 'childhero' 'childhood' 'children'
 'chill' 'chimcbrid' 'chimp' 'china' 'chines' 'chip' 'chipmunk'
 'chiwetelejiofor' 'chloëgracemoretz' 'chloësevigni' 'chocol' 'choic'
 'choos' 'chosen' 'chowyunfat' 'chri' 'chriscolumbu' 'chriscoop'
 'chrisevan' 'chrishemsworth' 'chrisklein' 'chrispin' 'chrispratt'
 'chrisrock' 'christ' 'christian' 'christianbal' 'christianslat'
 'christin' 'christinaappleg' 'christinaricci' 'christma' 'christmasparti'
 'christoph' 'christopherlloyd' 'christophermcdonald' 'christophernolan'
 'christopherplumm' 'christopherwalken' 'christophwaltz' 'chronicl'
 'chuck' 'church' 'cia' 'ciaránhind' 'cigarettesmok' 'cillianmurphi'
 'cinema' 'circl' 'circu' 'circuit' 'circumst' 'citi' 'citizen' 'civil'
 'civilian' 'civilwar' 'claim' 'clair' 'clairedan' 'claireforlani' 'clan'
 'clark' 'clash' 'class' 'classic' 'classmat' 'classroom' 'clean' 'clear'
 'clerk' 'client' 'cliffcurti' 'climat' 'climb' 'clinteastwood' 'cliqu'
 'cliveowen' 'clock' 'clone' 'clorisleachman' 'close' 'closer' 'clown'
 'club' 'clue' 'clutch' 'coach' 'coast' 'cocain' 'cocki' 'code' 'codi'
 'coffin' 'col' 'cold' 'coldwar' 'cole' 'colehaus' 'colin' 'colinfarrel'
 'colinfirth' 'collaps' 'colleagu' 'collect' 'collector' 'colleg' 'collid'
 'collin' 'collis' 'colombia' 'colonel' 'coloni' 'color' 'colorado' 'coma'
 'combat' 'combin' 'come' 'comeback' 'comed' 'comedi' 'comedian' 'comet'
 'comfort' 'comic' 'comicbook' 'comingofag' 'comingout' 'command'
 'commando' 'commerci' 'commit' 'common' 'commun' 'compani' 'companion'
 'compet' 'competit' 'complet' 'complex' 'complic' 'compos' 'compromis'
 'comput' 'computerviru' 'conan' 'concern' 'concert' 'conclus' 'concoct'
 'condit' 'conduct' 'confeder' 'confess' 'confid' 'confin' 'conflict'
 'confront' 'confus' 'congress' 'conman' 'connect' 'connecticut' 'conni'
 'connienielsen' 'connor' 'conquer' 'conscienc' 'consequ' 'conserv'
 'consid' 'conspir' 'conspiraci' 'constant' 'constantli' 'construct'
 'consum' 'contact' 'contain' 'contemporari' 'contend' 'content' 'contest'
 'contin' 'continu' 'contract' 'contractor' 'control' 'controversi'
 'convent' 'converg' 'convers' 'convict' 'convinc' 'cook' 'cool' 'cooper'
 'cop' 'cope' 'core' 'corner' 'corp' 'corpor' 'corps' 'corrupt' 'cost'
 'costar' 'costum' 'counselor' 'count' 'countess' 'counti' 'countless'
 'countri' 'countryhous' 'countrymus' 'countrysid' 'coup' 'coupl' 'courag'
 'cours' 'court' 'courtcas' 'courteneycox' 'courtroom' 'cousin' 'cover'
 'covert' 'coverup' 'covet' 'cow' 'cowardli' 'cowboy' 'cowork' 'coyot'
 'crab' 'crack' 'craft' 'craig' 'craigtnelson' 'crane' 'crash' 'crashland'
 'crave' 'crazi' 'creat' 'creation' 'creativ' 'creator' 'creatur' 'credit'
 'creepi' 'crew' 'cri' 'crime' 'crimefight' 'crimin' 'crisi' 'crispinglov'
 'critic' 'crocodil' 'crook' 'cross' 'crosscountri' 'crossdress'
 'crossroad' 'crowd' 'crown' 'crucifixion' 'cruel' 'cruelti' 'cruis'
 'crusad' 'crush' 'crystal' 'cuba' 'cubagoodingjr' 'culmin' 'cult'
 'cultfilm' 'cultur' 'cultureclash' 'cun' 'cup' 'cure' 'curios' 'current'
 'curs' 'curtishanson' 'custodi' 'custom' 'cut' 'cuttingthecord'
 'cyberpunk' 'cyborg' 'cynic' 'dad' 'daili' 'dakotafan' 'dale' 'damag'
 'damon' 'dan' 'danaykroyd' 'danc' 'dancer' 'danger' 'danhedaya' 'daniel'
 'danielcraig' 'danieldaylewi' 'danielradcliff' 'danni' 'dannyboyl'
 'dannydevito' 'dannyglov' 'dannyhuston' 'dannymcbrid' 'dannytrejo'
 'darci' 'dare' 'dark' 'darkcomedi' 'darkest' 'darylhannah' 'dash' 'date'
 'daughter' 'dave' 'davefranco' 'davi' 'david' 'davidarquett'
 'davidcronenberg' 'davidcross' 'davidduchovni' 'davidfinch'
 'davidgordongreen' 'davidkoechn' 'davidmors' 'davidorussel'
 'davidoyelowo' 'davidschwimm' 'davidspad' 'davidstrathairn' 'davidthewli'
 'daxshepard' 'day' 'daydream' 'dc' 'dccomic' 'dea' 'dead' 'deadli'
 'deadliest' 'deal' 'dealer' 'dean' 'death' 'deathofafriend' 'deathoffath'
 'deathpenalti' 'debramess' 'debt' 'debut' 'decad' 'decapit' 'deceas'
 'deceit' 'decept' 'decid' 'decis' 'declar' 'declin' 'dedic' 'deed' 'deep'
 'deeper' 'deepli' 'defeat' 'defend' 'defens' 'defi' 'deforestkelley'
 'delight' 'delinqu' 'deliv' 'deliveri' 'delroylindo' 'delus' 'demand'
 'demimoor' 'demon' 'demonicpossess' 'deni' 'deniserichard' 'denisleari'
 'denmark' 'denni' 'dennisdugan' 'dennisfarina' 'dennishopp' 'dennisquaid'
 'dentist' 'denzelwashington' 'depart' 'depend' 'depict' 'deport'
 'depress' 'depth' 'deputi' 'derang' 'derek' 'derekluk' 'dermotmulroney'
 'descend' 'describ' 'desert' 'design' 'desir' 'desk' 'desol' 'despair'
 'desper' 'despit' 'destin' 'destini' 'destroy' 'destruct' 'detect'
 'detent' 'determin' 'detroit' 'devast' 'develop' 'devic' 'devil' 'deviou'
 'devis' 'devot' 'diabol' 'diagnos' 'dialogu' 'diamond' 'dian'
 'dianekeaton' 'dianekrug' 'dianelan' 'diannewiest' 'diari' 'dick'
 'dictat' 'did' 'didnt' 'die' 'diego' 'diegoluna' 'differ' 'difficult'
 'difficulti' 'dig' 'digniti' 'dilemma' 'diner' 'dinner' 'dinosaur'
 'diplomat' 'dire' 'direct' 'director' 'dirt' 'dirti' 'dirtycop' 'disabl'
 'disappear' 'disast' 'disastr' 'discov' 'discoveri' 'diseas' 'disfigur'
 'disgrac' 'disguis' 'dishonesti' 'disillus' 'disney' 'disord' 'dispatch'
 'disrupt' 'distant' 'distract' 'district' 'distrust' 'disturb' 'ditch'
 'diva' 'dive' 'divid' 'divis' 'divorc' 'dj' 'djimonhouns' 'dna' 'doc'
 'dock' 'doctor' 'document' 'documentari' 'dodg' 'doe' 'doesnt' 'dog'
 'doll' 'dollar' 'dolphin' 'dolphlundgren' 'domest' 'domin' 'dominiccoop'
 'dominicwest' 'don' 'donaldfaison' 'donaldpetri' 'donaldsutherland'
 'donallogu' 'doncheadl' 'dont' 'doom' 'doomsday' 'door' 'doorstep'
 'doppelgang' 'dorothi' 'doubl' 'doublecross' 'doublelif' 'doubt' 'doug'
 'dougla' 'dougliman' 'dougrayscott' 'dr' 'dracula' 'drag' 'dragon'
 'drama' 'dramat' 'draw' 'drawn' 'dread' 'dream' 'dress' 'drew'
 'drewbarrymor' 'drift' 'drifter' 'drink' 'drive' 'driven' 'driver'
 'drone' 'drop' 'drown' 'drug' 'drugabus' 'drugaddict' 'drugdeal'
 'druglord' 'drugsmuggl' 'drugtraff' 'drugus' 'drunk' 'drunken'
 'dualident' 'dub' 'duck' 'dude' 'duel' 'duke' 'dump' 'dunn' 'duo' 'dure'
 'duringcreditssting' 'dustinhoffman' 'dutch' 'duti' 'dwarv'
 'dwaynejohnson' 'dyinganddeath' 'dylan' 'dylanbak' 'dynam' 'dynasti'
 'dysfunct' 'dysfunctionalfamili' 'dystopia' 'dystopicfutur' 'eager'
 'earli' 'earlier' 'earn' 'earth' 'earthquak' 'easi' 'easili' 'east' 'eat'
 'eccentr' 'econom' 'economi' 'eddi' 'eddiegriffin' 'eddiemurphi' 'edg'
 'edgar' 'edgarramírez' 'edharri' 'edhelm' 'editor' 'educ' 'edward'
 'edwardburn' 'edwardnorton' 'edwardzwick' 'effect' 'effort' 'egg' 'ego'
 'egypt' 'egyptian' 'el' 'elabor' 'elderli' 'elect' 'electr' 'element'
 'eleph' 'elev' 'eliaskotea' 'elijahwood' 'elimin' 'elisabethshu' 'elit'
 'elizabeth' 'elizabethbank' 'elizabethperkin' 'ella' 'ellefan'
 'ellenbarkin' 'ellenburstyn' 'ellenpag' 'elli' 'elliot' 'elliott' 'els'
 'elud' 'elus' 'elv' 'elvi' 'embark' 'embarrass' 'embassi' 'embroil'
 'emerg' 'emigr' 'emilehirsch' 'emili' 'emilyblunt' 'emilymortim'
 'emilywatson' 'emma' 'emmarobert' 'emmaston' 'emmathompson' 'emmawatson'
 'emot' 'emperor' 'empir' 'employ' 'employe' 'enabl' 'enchant' 'encount'
 'encourag' 'end' 'endless' 'endoftheworld' 'endur' 'enemi' 'energi'
 'enforc' 'engag' 'engin' 'england' 'english' 'enigmat' 'enjoy' 'enlist'
 'enorm' 'enrol' 'ensemblecast' 'enslav' 'ensu' 'ensur' 'entangl' 'enter'
 'enterpris' 'entertain' 'enthusiast' 'entir' 'entiti' 'entrepreneur'
 'environ' 'environment' 'epic' 'epidem' 'episod' 'equal' 'equip' 'era'
 'eric' 'ericbana' 'ericrobert' 'erin' 'ernest' 'erotic' 'erupt' 'escal'
 'escap' 'escapad' 'escapefromprison' 'escort' 'especi' 'espionag'
 'establish' 'estat' 'estrang' 'et' 'etern' 'ethan' 'ethanhawk' 'ethic'
 'eugenelevi' 'europ' 'european' 'eva' 'evacu' 'evad' 'evamend' 'evan'
 'evanrachelwood' 'eve' 'event' 'eventu' 'everi' 'everybodi' 'everyday'
 'everyon' 'everyth' 'everywher' 'evid' 'evil' 'evolut' 'evolv'
 'ewanmcgregor' 'ex' 'exact' 'exactli' 'exam' 'examin' 'exboyfriend'
 'exchang' 'excit' 'exclus' 'excon' 'excop' 'execut' 'exercis'
 'exgirlfriend' 'exhibit' 'exil' 'exist' 'existenti' 'exlov' 'exorc'
 'exot' 'exoticisland' 'expect' 'expedit' 'experi' 'experienc' 'expert'
 'explain' 'explod' 'exploit' 'explor' 'explos' 'expos'
 'extramaritalaffair' 'extraordinari' 'extraterrestri'
 'extraterrestrialtechnolog' 'extrem' 'extremeviol' 'exwif' 'eye' 'fabl'
 'face' 'facetofac' 'facil' 'fact' 'faction' 'factori' 'fade' 'fail'
 'fairi' 'fairytal' 'faith' 'fake' 'falcon' 'fall' 'fallen' 'fallinginlov'
 'fals' 'falseident' 'falselyaccus' 'fame' 'famili' 'familyrelationship'
 'familysdailylif' 'famkejanssen' 'famou' 'fan' 'fanat' 'fangvamp'
 'fantasi' 'fantast' 'fantasyworld' 'far' 'farewel' 'farm' 'farmer'
 'farmhous' 'fascin' 'fashion' 'fast' 'faster' 'fat' 'fatal' 'fate'
 'father' 'fatherdaughterrelationship' 'fatherinlaw'
 'fathersonrelationship' 'favor' 'favorit' 'fbi' 'fbiagent' 'fear'
 'fearless' 'fearsom' 'featur' 'feder' 'feel' 'feet' 'fellow' 'femal'
 'femalefriendship' 'femalenud' 'femaleprotagonist' 'fend' 'festiv' 'feud'
 'fgarygray' 'fiance' 'fiancé' 'fiction' 'fictionalplac' 'field' 'fierc'
 'fight' 'fighter' 'figur' 'file' 'film' 'filmdirector' 'filmmak'
 'filmproduc' 'final' 'financ' 'financi' 'fine' 'finish' 'finn' 'firemen'
 'firework' 'firm' 'firsttim' 'fish' 'fisherman' 'fishoutofwat'
 'fistfight' 'fit' 'fix' 'flame' 'flash' 'flashback' 'flat' 'fledgl'
 'flee' 'flesh' 'fli' 'flight' 'fling' 'flint' 'flirt' 'flood' 'florida'
 'flower' 'flyingsauc' 'focu' 'focus' 'foe' 'foil' 'folk' 'follow' 'food'
 'foot' 'footag' 'footbal' 'footchas' 'forbidden' 'forbiddenlov' 'forc'
 'ford' 'foreign' 'forest' 'forestwhitak' 'forev' 'forg' 'forget' 'forgiv'
 'form' 'formid' 'formula' 'fort' 'fortun' 'fortunetel' 'forward' 'foster'
 'fought' 'foundfootag' 'fourth' 'fox' 'frame' 'franc' 'francesfish'
 'francesmcdormand' 'franchis' 'franci' 'francisco' 'francisfordcoppola'
 'frank' 'frankenstein' 'franki' 'franklangella' 'frankoz' 'frantic'
 'fratern' 'fraud' 'freak' 'fred' 'freddi' 'freddieprinzejr' 'fredward'
 'free' 'freedom' 'freespirit' 'freez' 'french' 'frequent' 'fresh'
 'freshman' 'friend' 'friendli' 'friendship' 'frighten' 'frog' 'frontier'
 'frozen' 'frustrat' 'fu' 'fuel' 'fugit' 'fulfil' 'fulli' 'fun' 'fund'
 'funer' 'funni' 'furiou' 'futur' 'futurist' 'fword' 'ga' 'gabriel'
 'gabrielbyrn' 'gabrielleunion' 'gabrielmacht' 'gadget' 'gaelgarcíabern'
 'gain' 'galaxi' 'gambl' 'gambler' 'game' 'gandhi' 'gang' 'gangdu'
 'gangster' 'gangsterboss' 'gangwar' 'garag' 'garden' 'garfield' 'gari'
 'garretthedlund' 'garrymarshal' 'garyoldman' 'garysinis' 'gasstat' 'gate'
 'gather' 'gave' 'gay' 'gayinterest' 'gayrelationship' 'geek'
 'genehackman' 'gener' 'genet' 'geniu' 'genocid' 'genr' 'gentl'
 'geoffreyrush' 'georg' 'georgearomero' 'georgeclooney' 'georgemil'
 'georgetakei' 'georgewbush' 'georgia' 'gerardbutl' 'german' 'germani'
 'getaway' 'ghetto' 'ghost' 'gi' 'giancarloesposito' 'giant' 'giantrobot'
 'gift' 'gig' 'gilliananderson' 'giovanniribisi' 'girl' 'girlfriend'
 'given' 'gladiat' 'glamor' 'glass' 'glennclos' 'glenneheadli' 'global'
 'globe' 'glori' 'goal' 'god' 'goe' 'gold' 'golden' 'golf' 'gone' 'good'
 'goodvsevil' 'goon' 'goranvisnj' 'gordon' 'gore' 'goreverbinski'
 'gorgeou' 'gorilla' 'gossip' 'got' 'gotham' 'gothamc' 'govern' 'governor'
 'grace' 'grade' 'gradual' 'graduat' 'grand' 'granddaught' 'grandfath'
 'grandmoth' 'granni' 'grant' 'graphic' 'grasp' 'grave' 'great' 'greater'
 'greatest' 'greec' 'greed' 'greedi' 'greek' 'green' 'greg' 'gregghenri'
 'gregkinnear' 'gregorypeck' 'grew' 'grief' 'griev' 'griffin' 'grim'
 'grip' 'grisli' 'gritti' 'ground' 'group' 'groupoffriend' 'grow'
 'growingup' 'grown' 'gruesom' 'guard' 'guardian' 'guerrilla' 'guest'
 'guid' 'guidanc' 'guilt' 'guilti' 'guitar' 'gun' 'gunfight' 'gunman'
 'gunsling' 'guru' 'gusvans' 'guy' 'guypearc' 'guyritchi' 'gwynethpaltrow'
 'gym' 'gypsi' 'gérarddepardieu' 'ha' 'habit' 'hack' 'hacker' 'hair'
 'haleyjoelos' 'half' 'halfway' 'hall' 'halleberri' 'halloween' 'hallucin'
 'han' 'hand' 'handl' 'handsom' 'handtohandcombat' 'hang' 'hangov'